name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create application.properties
        run: |
          echo "${{ secrets.APPLICATION_PROPERTIES }}" > src/main/resources/application.properties

      - name: Java setup
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: List build files (Debugging)
        run: ls -lh build/libs/

      - name: debug files
        run: ls -lh

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-jar
          path: build/libs/MySelectShop-0.0.1-SNAPSHOT.jar

      - name: Upload Docker file
        uses: actions/upload-artifact@v3
        with:
          name: my-dockerfile
          path: Dockerfile