name: Deploy

on:
  workflow_run:
    workflows: ["Integration"]
    types:
      - completed

jobs:
  build_deploy:
    runs-on: [ ubuntu-latest ]

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Docker 실행 중인 컨테이너 중지
            sudo docker stop my-select-shop || true
            sudo docker rm my-select-shop || true

            # 최신 Docker 이미지 가져오기
            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/my-select-shop:latest

            # 컨테이너 실행
            sudo docker run -d --name my-select-shop -p 8080:8080 ${{ secrets.DOCKER_HUB_USERNAME }}/my-select-shop:latest