name: Integration

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  build_deploy:
    runs-on: [ ubuntu-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: List build files (Debugging)
        run: ls -lh build/libs/

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/my-select-shop:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-select-shop:latest